### ISSUE TITLE
The gateway can't find the "app1" service

### ISSUE THREAD

**Issue by jdubois** [jhipster/jhipster-experimental-microservices#1]
I've spent a lot of time on this, and I can't have a correct configuration, so any help here is very, very welcome.

In the current configuration:
- The Gateway and App1 are correctly registered in the Registry
- Inside the Gateway, using the DiscoveryClient bean, we see the "app1" service, doing a `discoveryClient.getServices()` but doing a `discoveryClient.getInstances("app1")` returns an empty list...
- Requesting with Gateway with http://127.0.0.1:8080/app1/api/foos returns a Zuul error telling `Load balancer does not have available server for client: app1`, which is logical as on the previous point the service couldn't be found...

I don't understand the problem here, as:
- "App1" is correctly registered in the registry, going to http://127.0.0.1:8761/ it is available and "UP"
- The service ID is seen from the Gateway, you even see it going to the health page at http://127.0.0.1:8080/#/health

**Comment by rafoli** [comment]
Hi @jdubois, you just have to configure the spring.application.name in order to enable the context 'app1' to be visible using http://127.0.0.1:8080/app1/api/foos, if none it will be available at http://127.0.0.1:8080/api/foos
