### ISSUE TITLE
Microservice composition

### ISSUE THREAD

**Issue by eallais** [jhipster/jhipster-experimental-microservices#13]
I wonder if each microservice registered in the gateway are autonomous or can be coupled?
For example, a microservice **app1** could reach another microservice **app2**?

**Comment by jdubois** [comment]
They can see each other, and even discover themselves through the registry. So it's certainly doable.
But we currently don't provide any helper for that.

**Comment by cbornet** [comment]
You can have a look at my [generator-jhipster-swagger-cli](https://github.com/cbornet/generator-jhipster-swagger-cli) module that can help with this.

**Comment by PierreBesson** [comment]
You can use Feign (rest client library), it can plays nicely with Eureka (see one example here: [spring-cloud-samples/feign-eureka](https://github.com/spring-cloud-samples/feign-eureka)).
You can do @FeignClient("microserviceName") to consume it. It is one of my ideas to try to do a generator using that in @cbornet's module.
