### ISSUE TITLE
Centralized configuration

### ISSUE THREAD

**Issue by eallais** [jhipster/jhipster-experimental-microservices#14]
It would be interesting to centralized the configuration of each microservice (or the whole stack) by using the **spring cloud config** project.
The gateway could be the config server.

**Comment by jdubois** [comment]
good point cc @PierreBesson 
I'm currently comparing Archaius vs Spring Cloud Config server
And I'm also planning of having the registry + config server together -> don't you think it's more logical than the gateway?

**Comment by PierreBesson** [comment]
@jdubois 
I just tested Spring Cloud Config server following the [spring guide](https://spring.io/guides/gs/centralized-configuration/) and the [documentation](http://cloud.spring.io/spring-cloud-config/spring-cloud-config.html) and I have been able to embed the config server in the registry and configure a client. It is really simple to set up.

**Comment by jdubois** [comment]
I've looked at it and I like the way it is working with Git, so you can easily tag your configuration -> looks better than Archaius in my opinion, because of this feature.
Could you add you code to https://github.com/jhipster/jhipster-registry ?
I'm thinking of having just one central source for configuration and resource discovery, as it would be simpler to set up in dev and prod.
Then, the issue is that we need a Git server -> do you think you could do a docker compose file with everything setup in one simple step?

**Comment by PierreBesson** [comment]
Actually it also supports config from plain text files ! I have already done it. And then if the users want it they can configure git by themselves, we can provide instructions.

**Comment by PierreBesson** [comment]
And even if we use git, there is actually no need for a git server, just a local git repository did the job in my tests.

**Comment by jdubois** [comment]
Oh yes you are right, so in dev mode it should just be the text file.
And in prod it's either an external Git server (that the user needs to configure) or a Git server launched with Docker Compose

**Comment by PierreBesson** [comment]
OK, I will look into git servers that we could use. Would you like one with a graphical interface that can edit text files ?

**Comment by jdubois** [comment]
You mean with some kind of Web UI on top of the Git server?

**Comment by PierreBesson** [comment]
Yes. Since I know you can do that in Github and Gitlab.

**Comment by jdubois** [comment]
I'm not sure everyone will want this, so don't do it for the moment -> it's more work
Maybe in the future we could have 2 docker compose, one with the UI and one without

**Comment by PierreBesson** [comment]
OK, I'm also starting to think that it is not that important...

**Comment by jdubois** [comment]
Done
