### ISSUE TITLE
Use of a configuration service

### ISSUE THREAD

**Issue by josedab** [jhipster/jhipster-experimental-microservices#16]
Was wondering if it would be useful to add a configuration service to the list of the services already in use.
Possible improvements with this adoption will be:
- Configuration centralized (only configuration service in charge rather than each service on its own)
- Dynamic reload of properties (spring cloud config could do it by itself)

A possible way to do it:
- Use of spring-cloud-config artifact
- Use bootstrap.properties instead of application.{properties|yaml} on the services that connect to the configuration service

If this is something useful that the team is looking in the future, I would be happy to provide examples/code/suggestions. 
I did an exercise integrating several components of spring cloud if you think it could help in any way:
https://github.com/josedab/spring-cloud-examples/tree/master/zipkin-distributed-tracing

**Comment by jdubois** [comment]
We already have this :-)
You are on the test, "experimental" repo, we've gone much further in the real repo now :-)
