### ISSUE TITLE
How to run Microservice application + gateway. (without Docker)

### ISSUE THREAD

**Issue by MBenali** [jhipster/jhipster-experimental-microservices#17]
Hello,
i generate WITH YO JHIPSTER two applications, Microservice application 'ms_app' and Microservice gateway 'gw_app' and download jhipster-registry,
i Run mvn on each project to get them running

when i open link : http://127.0.0.1:8761/, i show under : 'Instances currently registered with Eureka' my two applications : 
GW_APPLI    n/a (1)     (1)     UP (1) - gw_appli:c900c371cac17460a21c945ca796f715
MS_APPLI    n/a (1)     (1)     UP (1) - ms_appli:ef082ade32a044bfc19fe4c02fe1324a

when open link : http://127.0.0.1:8081/  i have this message : "Your request cannot be processed'
**AND A WHITE page** for : http://127.0.0.1:8080/

how to have the same things as in this video  "JHipster 3.0 night! - Singapore Spring User Group", LINK : [ https://www.youtube.com/watch?v=nKRpVkba4Ck ] at 1h08minutes

like a result i have with a monolithic application (authentication, add some entities and services ... etc.)

Thanks

**Comment by pascalgrimaud** [comment]
Hello,
Plz, don't open issue on "deprecated" project.
I have absolutely no problem to start all applications without Docker:
- start registry with `mvn` and access to http://localhost:8761
- start gateway with `mvn` and access to http://localhost:8080

About white page, run manually :
1. `npm install`
2. `bower install`
3. `gulp install`

**Comment by MBenali** [comment]
thanks

i still have errors (environnement errors --> Bower packages) : 
when run : gulp install
gulp-notify: [JHipster Gulp Build] Error: Error: Cannot find where you keep your Bower packages.

when run ; gw_appli $*\* mvn spring-boot:run**
gw_appli:350113317acf23e4f0a368d4b22a8deb - **## registration status: 204**
2016-05-08 22:52:13.956 ERROR 16618 --- [           main] o.s.boot.SpringApplication               : Application startup failed

**Comment by jdubois** [comment]
Please don't comment on old issues.
This is an old deprecated repo, we don't provide help on it.

**Comment by MBenali** [comment]
sorry,
thanks
