### ISSUE TITLE
Centralized logging

### ISSUE THREAD

**Issue by jdubois** [jhipster/jhipster-experimental-microservices#5]
We could have a server using the ELK stack that processes our logs, so we could monitor everything easily.

[This tutorial](http://knes1.github.io/blog/2015/2015-08-16-manage-spring-boot-logs-with-elasticsearch-kibana-and-logstash.html) shows how to send all logs from Spring Boot to ELK, so this should be quite easy to do.

We should also:
- See how logs should be sent: using files might not be the best option, maybe they could be sent over a socket to the ELK server?
- Provide some security on the Kibana dashboard
- Have some default dashboards

**Comment by pascalgrimaud** [comment]
Just to let you know that I followed [this tutorial](http://knes1.github.io/blog/2015/2015-08-16-manage-spring-boot-logs-with-elasticsearch-kibana-and-logstash.html) and it works fine to monitor a JHipster application.

I did it in the [JHipster Docker module](https://github.com/pascalgrimaud/generator-jhipster-docker) :
- [elk.yml](https://github.com/pascalgrimaud/generator-jhipster-docker/blob/master/generators/app/templates/src/main/docker/_elk.yml)
- [logstash.conf](https://github.com/pascalgrimaud/generator-jhipster-docker/blob/master/generators/app/templates/src/main/docker/logstash/_logstash.conf)

At the moment, it works with logs, and not socket

It will be easy to extend to registry, gateway, etc...

**Comment by jdubois** [comment]
Thanks! Yes that's perfectly what we need!

**Comment by jdubois** [comment]
Done
